
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '', url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'fitness_scoring.views.login_user'),
    url(r'^login', 'fitness_scoring.views.login_user', name='login'),
    url(r'^logout/', 'fitness_scoring.views.logout_user', name='logout'),
    url(r'^teacher_view/', 'fitness_scoring.views.teacher_view', name='teacher_view'),
    url(r'^teacher_home/', 'fitness_scoring.views.teacher_home', name='teacher_home'),
    url(r'^administrator_view/$', 'fitness_scoring.views.administrator_view', name='administrator_view'),
    url(r'^administrator_home/', 'fitness_scoring.views.administrator_home', name='administrator_home'),
    url(r'^superuser_view/', 'fitness_scoring.views.superuser_view', name='superuser_view'),
    url(r'^superuser_home/', 'fitness_scoring.views.superuser_home', name='superuser_home'),
    url(r'^school/list/', 'fitness_scoring.views.school_list', name='school_list'),
    url(r'^school/add/', 'fitness_scoring.views.school_add', name='school_add'),
    url(r'^school/adds/', 'fitness_scoring.views.school_adds', name='school_adds'),
    url(r'^school/edit/(?P<school_pk>\d+)', 'fitness_scoring.views.school_edit', name='school_edit'),
    url(r'^school/delete/(?P<school_pk>\d+)', 'fitness_scoring.views.school_delete', name='school_delete'),
    url(r'^test_category/list/', 'fitness_scoring.views.test_category_list', name='test_category_list'),
    url(r'^test_category/add/', 'fitness_scoring.views.test_category_add', name='test_category_add'),
    url(r'^test_category/adds/', 'fitness_scoring.views.test_category_adds', name='test_category_adds'),
    url(r'^test_category/edit/(?P<test_category_pk>\d+)', 'fitness_scoring.views.test_category_edit',
        name='test_category_edit'),
    url(r'^test_category/delete/(?P<test_category_pk>\d+)', 'fitness_scoring.views.test_category_delete',
        name='test_category_delete'),
    url(r'^test/list/', 'fitness_scoring.views.test_list', name='test_list'),
    url(r'^test/add/', 'fitness_scoring.views.test_add', name='test_add'),
    url(r'^test/adds/', 'fitness_scoring.views.test_adds', name='test_adds'),
    url(r'^test/edit/(?P<test_pk>\d+)', 'fitness_scoring.views.test_edit', name='test_edit'),
    url(r'^test/delete/(?P<test_pk>\d+)', 'fitness_scoring.views.test_delete', name='test_delete'),
    url(r'^student/list/', 'fitness_scoring.views.student_list', name='student_list'),
    url(r'^student/list2/', 'fitness_scoring.views.student_list2', name='student_list2'),
    url(r'^student/add/', 'fitness_scoring.views.student_add', name='student_add'),
    url(r'^student/adds/', 'fitness_scoring.views.student_adds', name='student_adds'),
    url(r'^student/edit/(?P<student_pk>\d+)', 'fitness_scoring.views.student_edit', name='student_edit'),
    url(r'^student/delete/(?P<student_pk>\d+)', 'fitness_scoring.views.student_delete', name='student_delete'),
    url(r'^teacher/list/', 'fitness_scoring.views.teacher_list', name='teacher_list'),
    url(r'^teacher/add/', 'fitness_scoring.views.teacher_add', name='teacher_add'),
    url(r'^teacher/adds/', 'fitness_scoring.views.teacher_adds', name='teacher_adds'),
    url(r'^teacher/edit/(?P<teacher_pk>\d+)', 'fitness_scoring.views.teacher_edit', name='teacher_edit'),
    url(r'^teacher/delete/(?P<teacher_pk>\d+)', 'fitness_scoring.views.teacher_delete', name='teacher_delete'),
    url(r'^class/list/', 'fitness_scoring.views.class_list', name='class_list'),
    url(r'^class/add/', 'fitness_scoring.views.class_add', name='class_add'),
    url(r'^class/adds/', 'fitness_scoring.views.class_adds', name='class_adds'),
    url(r'^class/edit/(?P<class_pk>\d+)', 'fitness_scoring.views.class_edit', name='class_edit'),
    url(r'^class/delete/(?P<class_pk>\d+)', 'fitness_scoring.views.class_delete', name='class_delete'),
)
